services:
  backend:
    image: misetius/backend:development-test
    ports:
      - "8000:8000"
    environment:
      - ANALYSIS_SERVICE_URL=http://analysis:8001
      - PORT=8000
      - DATABASE_HOST=postgres
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=finance_db
    depends_on:
      - postgres

  analysis:
    image: misetius/analysis:development-test
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_HOST=postgres
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=finance_db
    depends_on:
      - postgres


  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
 


