apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base




images:
- name: analysis/image
  newName: misetius/analysis
  newTag: ba2a87f73436b77a6e8ee5ba92925fc7bb774ecb
- name: backend/image
  newName: misetius/backend
  newTag: ba2a87f73436b77a6e8ee5ba92925fc7bb774ecb
- name: frontend/image
  newName: misetius/frontend
  newTag: ba2a87f73436b77a6e8ee5ba92925fc7bb774ecb
