apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base




images:
- name: analysis/image
  newName: misetius/analysis
  newTag: 50c9f3c27174507c3422c231b5645774f3ce8e43
- name: backend/image
  newName: misetius/backend
  newTag: 50c9f3c27174507c3422c231b5645774f3ce8e43
