apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base




images:
- name: analysis/image
  newName: misetius/analysis
  newTag: 4d681ed1e17d7033d36b40b1fa1a5840004006c1
- name: backend/image
  newName: misetius/backend
  newTag: 4d681ed1e17d7033d36b40b1fa1a5840004006c1
- name: frontend/image
  newName: misetius/frontend
  newTag: 4d681ed1e17d7033d36b40b1fa1a5840004006c1
