apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base




images:
- name: analysis/image
  newName: misetius/analysis
  newTag: 5dd4fc02a4b5d4bae23cb5ca30bf3c841d2e7254
- name: backend/image
  newName: misetius/backend
  newTag: 5dd4fc02a4b5d4bae23cb5ca30bf3c841d2e7254
- name: frontend/image
  newName: misetius/frontend
  newTag: 5dd4fc02a4b5d4bae23cb5ca30bf3c841d2e7254
