apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base




images:
- name: analysis/image
  newName: misetius/analysis
  newTag: 58dd0946b195076208848e0aaec3e37f2fb67ab5
- name: backend/image
  newName: misetius/backend
  newTag: 58dd0946b195076208848e0aaec3e37f2fb67ab5
- name: frontend/image
  newName: misetius/frontend
  newTag: 58dd0946b195076208848e0aaec3e37f2fb67ab5
