apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base




images:
- name: analysis/image
  newName: misetius/analysis
  newTag: production
- name: backend/image
  newName: misetius/backend
  newTag: production
- name: frontend/image
  newName: misetius/frontend
  newTag: production


