apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-web-app-analysis
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: finance-web-app-analysis
  template:
    metadata:
      labels:
        app: finance-web-app-analysis
    spec:
      containers:  
        - name: analysis
          image: analysis/image
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3002"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_HOST
              value: "database"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER 
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB