apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-web-app-backend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: finance-web-app-backend
  template:
    metadata:
      labels:
        app: finance-web-app-backend
    spec:
      containers: 
        - name: backend
          image: backend/image
          imagePullPolicy: Always
          env:
            - name: ANALYSIS_SERVICE_URL
              value: "http://analysis-svc:2346/"
            - name: PORT
              value: "3001"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_HOST
              value: "database"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER 
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB


        