apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: analysis-svc
spec:
  type: ClusterIP
  selector:
    app: analysis
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3002
